<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>main page</title>
</head>
<body>

<div> <a href="http://localhost:8080/"><h3 style="float: left">main page</h3>  </a></div>
<br/><br/><br/>


<form name="upload" action="upload" method="post", enctype="multipart/form-data">
    <h3> upload file </h3> <input type="file" name="uploadfile">
    <br/><br/>
    <input type="submit" value="analysis">
</form>

</body>
</html>